import { SoundName } from "./types";

export const SOUND_MAP: { [key in SoundName]: string } = {
  "join-music": "/sounds/mojuo.mp3",
  "join-player-joined": "/sounds/dbz_instant_trans.mp3",
  "rps-show-move": "/sounds/spinning_heart.mp3",
  "rps-result-win": "/sounds/winner.mp3",
  "rps-result-draw": "/sounds/crowd_oooo.mp3",
  "rps-new-round": "/sounds/soft_sound.mp3",
  "rps-game-on": "/sounds/bally_slot_win.mp3",
  "rps-front-runners": "/sounds/sparkle.mp3",
  "rps-could-win-next-round": "/sounds/dun_dun_dun.mp3",
  "rps-definite-winner": "/sounds/second_fanfare.mp3",
  "rps-spectator-chooses-option": "/sounds/bubble_pop.mp3",
  "rps-waiting-music": "/sounds/bally_slot_big_win.mp3",
  "rps-spectator-choice-reveal": "/sounds/bubble_pop.mp3",
  "rps-award-winner": "/sounds/nfl.mp3",
  "rps-award-loser": "/sounds/wah_wah_wah.mp3",
  "rps-award-middle": "/sounds/meh.mp3",
  "whos-that": "/sounds/whos-that-pokemon.mp3",
  "ai-thinking": "/sounds/processing.mp3",
  "ai-speaking": "/sounds/robot_beeps.mp3",
  "ai-typing": "/sounds/keyboard_typing.mp3",
  "gas-play-number-card": "/sounds/dbz_instant_trans.mp3",
  "gas-play-reverse-card": "/sounds/dbz_instant_trans.mp3",
  "gas-play-skip-card": "/sounds/dbz_instant_trans.mp3",
  "gas-play-risky-card": "/sounds/dbz_instant_trans.mp3",
  "gas-play-survived-risk": "/sounds/dbz_instant_trans.mp3",
  "gas-cursed": "/sounds/dbz_instant_trans.mp3",
  "gas-inflate": "/sounds/dbz_instant_trans.mp3",
  "gas-explode": "/sounds/dbz_instant_trans.mp3",
  "gas-player-die": "/sounds/dbz_instant_trans.mp3",
  "gas-winner": "/sounds/dbz_instant_trans.mp3",
  "gas-head-to-head-round": "/sounds/dbz_instant_trans.mp3",
  "gas-background-music": "/sounds/dbz_instant_trans.mp3",
};
