export type SoundName =
  | "join-music"
  | "join-player-joined"
  | "rps-show-move"
  | "rps-result-win"
  | "rps-result-draw"
  | "rps-new-round"
  | "rps-game-on"
  | "rps-front-runners"
  | "rps-could-win-next-round"
  | "rps-definite-winner"
  | "rps-waiting-music"
  | "rps-spectator-chooses-option"
  | "rps-spectator-choice-reveal"
  | "rps-award-winner"
  | "rps-award-loser"
  | "rps-award-middle";
